version: '3'
services:
  dev:
    command: sleep infinity
    build:
      context: .
    volumes:
      - ..:/workspace
      - ~/.ssh:/home/cirrus/.ssh
      - ~/.gnupg:/home/cirrus/.gnupg
      - ~/.gitconfig:/home/cirrus/.gitconfig
    privileged: true
    ports:
      - "3000:3000"
